services:
  app: &main
    build: .
    image: keboola/dbt-transformation
    volumes:
      - ./:/code
      - ./data:/data

  dev:
    <<: *main
    environment:
      PGSQL_DB_HOST: pgsql
      PGSQL_DB_PORT: 5432
      PGSQL_DB_USER: postgres
      PGSQL_DB_PASSWORD: some password
      PGSQL_DB_DATABASE: postgres
      PGSQL_DB_SCHEMA: public
      MSSQL_DB_HOST: mssql
      MSSQL_DB_PORT: 1433
      MSSQL_DB_USER: SA
      MSSQL_DB_PASSWORD: Passw@rd
      MSSQL_DB_SCHEMA: dbo
      MSSQL_DB_DATABASE: test
      KBC_DATA_TYPE_SUPPORT: none
    links:
      - pgsql
      - mssql

  pgsql:
    image: postgres
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some password
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  mssql:
    build: ./docker/mssql
    ports:
      - '1433:1433'

  wait:
    image: waisbrot/wait
    depends_on:
      - pgsql
      - mssql
    environment:
      - TARGETS=pgsql:5432,mssql:1433
      - TIMEOUT=200
