<?php

declare(strict_types=1);

namespace DbtTransformation\FileDumper;

use DbtTransformation\Helper\YamlParseHelper;
use Keboola\Component\UserException;
use Psr\Log\LoggerInterface;
use Symfony\Component\Yaml\Exception\ParseException;
use Symfony\Component\Yaml\Yaml;

class DbtProfilesYaml extends FilesystemAwareDumper
{
    public function __construct(private readonly LoggerInterface $logger)
    {
        parent::__construct();
    }

    /**
     * @param array<string, array<string, string|bool>> $outputs
     * @param array<string, string|bool|int|float> $additionalOptions Options injected into every output after merge
     * @throws UserException
     */
    public function dumpYaml(
        string $projectPath,
        string $profilesPath,
        array $outputs,
        array $additionalOptions = [],
    ): void {
        $dbtProjectYamlPath = sprintf('%s/dbt_project.yml', $projectPath);
        if (!$this->filesystem->exists($dbtProjectYamlPath)) {
            throw new UserException('Missing file "dbt_project.yml" in your project root');
        }
        $dbtProjectYaml = (array) YamlParseHelper::parseUserYamlFile($dbtProjectYamlPath, 'dbt_project.yml');
        if (!array_key_exists('profile', $dbtProjectYaml)) {
            throw new UserException('Missing key "profile" in "dbt_project.yml"');
        }
        if (!is_string($dbtProjectYaml['profile'])) {
            throw new UserException('Key "profile" in "dbt_project.yml" must be a string');
        }
        $profile = $dbtProjectYaml['profile'];

        $profilesYamlPath = sprintf('%s/profiles.yml', $profilesPath);
        if ($this->filesystem->exists($profilesYamlPath)) {
            $outputs = $this->mergeExistingOutputs($profilesYamlPath, $profile, $outputs);
        }

        if ($additionalOptions !== []) {
            foreach ($outputs as $outputName => $outputConfig) {
                if (is_array($outputConfig)) {
                    $outputs[$outputName] = array_merge($outputConfig, $additionalOptions);
                }
            }
        }

        $this->filesystem->dumpFile(
            $profilesYamlPath,
            Yaml::dump([
                'config' => ['send_anonymous_usage_stats' => false],
                $profile => [
                    'target' => 'dev',
                    'outputs' => $outputs,
                ],
            ], 5),
        );
    }

    /**
     * @param array<string, array<string, string|bool>> $outputs
     * @return array<string, array<string, string|bool>>
     * @throws UserException
     */
    private function mergeExistingOutputs(string $profilesYamlPath, string $profile, array $outputs): array
    {
        try {
            $profiles = (array) Yaml::parseFile($profilesYamlPath);
        } catch (ParseException $e) {
            if (!YamlParseHelper::containsJinja($e)) {
                throw YamlParseHelper::toUserException($e, 'profiles.yml');
            }
            $this->logger->warning(sprintf(
                'Could not parse existing profiles.yml because it contains Jinja templating: %s ' .
                'The file will be replaced by the profiles.yml generated by the component ' .
                'and its outputs will not be merged.',
                YamlParseHelper::sanitizeParseErrorMessage($e),
            ));
            return $outputs;
        }

        if (!array_key_exists($profile, $profiles)
            || !is_array($profiles[$profile])
            || !array_key_exists('outputs', $profiles[$profile])
        ) {
            return $outputs;
        }

        $existingOutputs = $profiles[$profile]['outputs'];
        if (!is_array($existingOutputs) || array_is_list($existingOutputs)) {
            $this->logger->warning(sprintf(
                'Existing profiles.yml has no valid "outputs" mapping for profile "%s"; nothing to merge. ' .
                'The file will be replaced by the generated profiles.yml.',
                $profile,
            ));
            return $outputs;
        }

        return array_merge($existingOutputs, $outputs);
    }
}
